version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    # Raise pull requests for version updates
    # to pip against the `develop` branch
    target-branch: "dev"
    # Labels on pull requests for version updates only
    labels:
      - "npm dependencies"
