site_name: '@pnp/spfx-controls-react'
nav:
  - Home: 'index.md'
  - Controls:
    - FileTypeIcon: 'controls/FileTypeIcon.md'
    - ListItemPicker: 'controls/ListItemPicker.md'
    - ListPicker: 'controls/ListPicker.md'
    - ListView: 'controls/ListView.md'
    - "ListView: add a contextual menu": 'controls/ListView.ContextualMenu.md'
    - Placeholder: 'controls/Placeholder.md'
    - SiteBreadcrumb: 'controls/SiteBreadcrumb.md'
    - WebPartTitle: 'controls/WebPartTitle.md'
    - SecurityTrimmedControl: 'controls/SecurityTrimmedControl.md'
    - TaxonomyPicker: 'controls/TaxonomyPicker.md'
    - PeoplePicker: 'controls/PeoplePicker.md'
    - IFrameDialog: 'controls/IFrameDialog.md'
  - 'Field Controls':
    - 'Getting started': 'controls/fields/main.md'
    - FieldRendererHelper: 'controls/fields/FieldRendererHelper.md'
    - FieldAttachmentsRenderer: 'controls/fields/FieldAttachmentsRenderer.md'
    - FieldDateRenderer: 'controls/fields/FieldDateRenderer.md'
    - FieldFileTypeRenderer: 'controls/fields/FieldFileTypeRenderer.md'
    - FieldLookupRenderer: 'controls/fields/FieldLookupRenderer.md'
    - FieldNameRenderer: 'controls/fields/FieldNameRenderer.md'
    - FieldTaxonomyRenderer: 'controls/fields/FieldTaxonomyRenderer.md'
    - FieldTextRenderer: 'controls/fields/FieldTextRenderer.md'
    - FieldTitleRenderer: 'controls/fields/FieldTitleRenderer.md'
    - FieldUrlRenderer: 'controls/fields/FieldUrlRenderer.md'
    - FieldUserRenderer: 'controls/fields/FieldUserRenderer.md'
  - 'Beta testing': 'beta.md'
  - About:
    - 'Release notes': 'about/release-notes.md'
    - License: 'about/license.md'
theme:
  name: 'material'
  palette:
    primary: 'blue'
  logo: 'assets/pnp-spfx-controls.svg'
  feature:
    tabs: true
extra_css:
  - 'css/extra.css'
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
extra:
  social:
    - type: 'twitter'
      link: 'https://twitter.com/officedevpnp'
    - type: 'youtube'
      link: 'http://aka.ms/sppnp-videos'
    - type: 'link'
      link: 'https://aka.ms/sppnp'
repo_url: https://github.com/SharePoint/sp-dev-fx-controls-react
edit_uri: blob/master/docs/documentation/docs
